steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-f", "Dockerfile.test.transformed", "-t", "gcr.io/$PROJECT_ID/dbt-test-transformed", "."]
  
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/dbt-test-transformed"]
  
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args: 
      - "run"
      - "jobs"
      - "deploy"
      - "dbt-test-transformed-job"
      - "--image=gcr.io/$PROJECT_ID/dbt-test-transformed"
      - "--region=europe-west1"
      - "--memory=2Gi"
      - "--max-retries=2"
      - "--task-timeout=1800"

images:
  - "gcr.io/$PROJECT_ID/dbt-test-transformed"