FROM python:3.11-slim

WORKDIR /app

# Install Python packages
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copy dbt project
COPY dbt_project.yml packages.yml profiles.yml ./
COPY models/ models/

# Run transformation ONLY (no tests)
CMD ["sh", "-c", "dbt deps && dbt run --select data-raw"]